### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by nobeh** [Narmnevis/range#8]
From a comment at PR#1:

> P.S. could you push library to Maven Central?

-- @Cka3o4Huk

**Comment by Cka3o4Huk** [comment]
Hi,

Any news? 

Thanks!

**Comment by nobeh** [comment]
@Cka3o4Huk I'm preparing for publishing to Maven Central. For that, I am polishing a bit; since you seem to be the major user of the library, is it OK if we bump the Java compile requirement to 1.8? Sorry for my delay on this issue.

**Comment by Cka3o4Huk** [comment]
Java8 is nice for me. Please ship it! :) :+1:

**Comment by nobeh** [comment]
range v1.3.2 is now on Maven Central.

**Comment by mizhka** [comment]
Many thanks!
